site_name: how do I pelican?
site_url: https://pages.charlesreid1.com/how-do-i-pelican
repo_name: charlesreid1/how-do-i-pelican
repo_url: https://github.com/charlesreid1/how-do-i-pelican
edit_uri: ""

copyright: 'Copyright &copy; 2018 <a href="https://charlesreid1.com">Charles Reid</a>, released under the <a href="https://opensource.org/licenses/MIT">MIT license</a>'

docs_dir: docs
site_dir: site
extra_css:
  - css/custom.css
theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'help'
  font:
    text: 'Bitter'
    code: 'PT Mono'
nav:
  - "Index" : "index.md"
  - "Before You Start" : "Before.md"
  - "Getting Started with Pelican" : "Getting.md"
  - "Configuring Your Pelican Site" : "Configuring.md"
  - "Theming Your Pelican Site" : "Theming.md"
  - "Generating Your Pelican Site" : "Generating.md"
  - "Serving Your Static Site" : "Serving.md"
  - "Adding Content" : "Adding.md"
  - "Hosting on Github Pages" : "Hosting.md"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


strict: true
